'use strict';
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
module.exports = function sidebar(mode, sections = []) {
  const deck = mode === 'deck', story = mode === 'story', tree = mode === 'decisions';
  const links = [['deck','index.html','Presentation'],['story','story.html','Scroll story'],['decisions','decisions.html','Decision tree'],['practices','best-practices.html','Best Practices']];
  const controls = deck || story ? `<div class="tools"><div class="view-switch" role="group" aria-label="Audience view"><button type="button" data-view="leader" aria-pressed="true">Leader</button><button type="button" id="audience-dev" data-view="dev" aria-pressed="false">Developer</button></div><button data-motion id="motion-toggle" type="button" aria-pressed="false">Pause motion</button>${story?'':'<button id="overview-toggle" type="button" aria-expanded="false" aria-controls="overview">Slide overview</button>'}<details class="presentation-options"><summary>Presentation options</summary><div class="option-panel"><button id="print" type="button">Print / PDF</button><button id="fullscreen" type="button">Full screen</button></div></details>${story?'<button id="overview-toggle" hidden type="button"></button>':''}</div>` : tree ? '<div class="controls"><button id="flat" aria-pressed="false">3D depth: on</button><button id="pause" aria-pressed="false">Pause motion</button></div>' : '<div class="controls"><button id="practice-print" type="button">Print practices</button></div>';
  const entries = sections.map((s,i)=>`<a href="#${esc(s.id)}"><span class="nav-index">${String(i+1).padStart(2,'0')}</span>${esc(s.label||s.title)}</a>`).join('');
  return `<details class="site-navigation" open><summary class="sidebar-toggle"><span>PREFRONTAL</span><span>Menu</span></summary><aside class="site-sidebar rail" aria-label="Site navigation"><a class="identity" href="index.html"><span>PREFRONTAL<br><strong>GOVERNED CONTEXT</strong></span></a><p class="rail-caption">Product concept · pilot pitch</p><nav class="site-formats" aria-label="Presentation format">${links.map(([id,href,label])=>`<a class="${(deck&&id==='story'||story&&id==='deck')?'presentation-format ':''}${id==='decisions'?'decision-format':''}" href="${href}"${id===mode?' aria-current="page"':''}>${label}<span aria-hidden="true">↗</span></a>`).join('')}</nav><div class="sidebar-actions"><a class="primary-action" href="${deck||story?'#full-architecture':tree?'#submit':'index.html#full-architecture'}">${tree?'Follow the first decision':'Explore the architecture'} ↗</a><a class="secondary-action" href="${deck||story?'#pilot-acceptance':'index.html#pilot-acceptance'}">Review the pilot →</a></div>${controls}<div class="sidebar-sections">${deck?'<details open class="section-menu"><summary>16 slides</summary><nav id="slide-nav" aria-label="Choose a slide"></nav><noscript><nav class="static-slide-nav" aria-label="Static slides">'+sections.map((s,i)=>`<a href="#static-${esc(s.id)}">${String(i+1).padStart(2,'0')} ${esc(s.title)}</a>`).join('')+'</nav></noscript></details>':story?'<nav id="slide-nav" hidden></nav><noscript><nav class="static-slide-nav" aria-label="Static chapters">'+sections.map((s,i)=>`<a href="#static-${esc(s.id)}">${String(i+1).padStart(2,'0')} ${esc(s.title)}</a>`).join('')+'</nav></noscript>':`<details open class="section-menu"><summary>${tree?'Journey phases':'Practice topics'}</summary><nav class="${tree?'phases':'practice-chapters'}" aria-label="${tree?'Journey phases':'Practice topics'}">${entries}</nav></details>`}</div><div class="sidebar-context" hidden></div><div class="sidebar-bottom">${deck||story?'<div class="pager"><button id="previous" type="button" aria-label="Previous slide">← Previous</button><span id="slide-count" aria-live="polite">—</span><button id="next" type="button" aria-label="Next slide">Next →</button></div>':''}<a class="cortex-nav-link${!tree?' js-only':''}" href="${story||tree?'':'story.html'}#why-prefrontal">Why Prefrontal?</a>${!tree?`<noscript><a href="${story?'':'story.html'}#static-why-prefrontal">Why Prefrontal?</a></noscript>`:''}<a href="motion-preview.html">Motion reference ↗</a><small>STE-inspired · compliance unchecked</small></div></aside></details>`;
};
